### ISSUE TITLE
Vue環境構築

### ISSUE THREAD

**Issue by tojimasan** [recursion-team-o/typing-game#2]
- [x] nodeのバージョンを16.14.0にする
- [x] create-vueで環境構築をする
https://reffect.co.jp/vue/create-vue
 - Type Script:Yes
 - JSX:No
 - Vue Router:Yes
 - Pinia:Yes
 - Vitest
 - Cypress
 - ESLint
- [x] 動作確認 
- [x] TailwindCSSの導入

**Comment by hata8341** [comment]
環境構築、完了

**Comment by tojimasan** [comment]
みなさん環境構築が完了したのでclose
