### ISSUE TITLE
データ構造のピニアのページを作成

### ISSUE THREAD

**Issue by Lukeyusukemiura** [recursion-team-o/typing-game#38]
## 背景・要望
-- ユーザーデータの保存場所、ソースコード保存
<img width="725" alt="Screen Shot 2022-03-15 at 16 08 58" src="https://user-images.githubusercontent.com/63922973/158324894-e0ae7c5c-dfcc-4c26-a44d-b85344fe2fe1.png">
場所を作成した方が今後の作業がうまくいく

-- 状態まで定義できればあとは、機能別に関数を加えていくことができる

## 開発内容
-- Storesファイルに新しいuser.ts、code.tsというファイルを作成
-- その中に各データを定義する

## やりたいこと
--

**Comment by haruki111** [comment]
code.tsのコード<string>は、myCordか用意したコードの違いしかないため、一つの変数にまとめて良いと思います。

myCordか用意したコードの判定は別の変数で保存
