### ISSUE TITLE
BGM再生機能の作成

### ISSUE THREAD

**Issue by hata8341** [recursion-team-o/typing-game#59]
## 背景・要望
- BGMや効果音を再生したい
## 開発内容
- 音楽on/off機能
- ミュート機能
- ボリューム調整機能
## やりたいこと
- 画面上でBGMの再生、停止、調整がしたい
## 満たすべき仕様
- 音楽on/off機能,ミュート機能,ボリューム調整機能が利用できる

**Comment by haruki111** [comment]
音楽on/offとミュートは同じですよね？

音楽のselectは後日で

**Comment by hata8341** [comment]
完
